### ISSUE TITLE
Support fetching price of crvEURSUSDC 

### ISSUE THREAD

**Issue by jstashh** [yearn/yearn-lens#15]
### Problem
The price of the crvEURSUSDC token (0x3d229e1b4faab62f621ef2f6a610961f7bd7b23b) fetched by the oracle is incorrect 
https://curve.fi/eursusd

### To reproduce
1. Go to the curve calculations contract at https://etherscan.io/address/0x94734ba0f9f8c2464d963a402743fd79b402efd7#readContract
2. Call `getPriceUsdc` using the crvEURSUSDC token
3. The result is ~$1.07

An alternate way:
1. Go to the curve calculations contract at https://etherscan.io/address/0x94734ba0f9f8c2464d963a402743fd79b402efd7#readContract
2. Call `cryptoPoolTokenAmountUsdc(0x98a7f18d4e56cfe84e3d081b40001b3d5bd3eb8b, 1)
3. The call reverts 

### Desired behavior
The price is 1 usdc + 1 eurs (~$2.12)

### Root of the problem
This line calls the pool's `price_oracle` function https://github.com/yearn/yearn-lens/blob/master/contracts/Oracle/Calculations/Curve.sol#L202
However the pool at 0x98a7f18d4e56cfe84e3d081b40001b3d5bd3eb8b does not take any arguments for the `price_oracle` function, it always passes back the price of eurs as we can assume that's the only price being queried, as opposed to e.g. the tricrypto pool which has multiple coins 

New functionality should be covered by new unit tests

**Comment by 0xfoursee** [comment]
Is this issue still relevant? I was gonna have a crack at it since it's an appealing first issue but seems like this has already been [fixed & merged](https://github.com/yearn/yearn-lens/pull/16) right?

**Comment by jstashh** [comment]
@0xfoursee Hey, sorry yes I had to do it as it was a bit urgent and the fix was a bit more complicated than I originally thought
